# Generated by Django 4.0.2 on 2022-05-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0002_alter_repre_vfname_alter_repre_vlname'),
    ]

    operations = [
        migrations.AddField(
            model_name='faci',
            name='Add',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='faci',
            name='mName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='faci',
            name='pNum',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='voter',
            name='scheduled',
            field=models.BooleanField(default=False, verbose_name='scheduled'),
        ),
    ]
