# Generated by Django 4.0.2 on 2022-05-08 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0003_faci_add_faci_mname_faci_pnum_voter_scheduled'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='scheduleddate',
            field=models.DateField(default=datetime.date.today, verbose_name='scheduledate'),
        ),
    ]
