# Generated by Django 4.0.2 on 2022-05-08 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0004_voter_scheduleddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='repre',
            name='scheduled',
            field=models.BooleanField(default=False, verbose_name='scheduled'),
        ),
        migrations.AddField(
            model_name='repre',
            name='scheduleddate',
            field=models.DateField(default=datetime.date.today, verbose_name='scheduledate'),
        ),
    ]
