# Generated by Django 4.0.2 on 2022-05-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0005_repre_scheduled_repre_scheduleddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repre',
            name='scheduleddate',
            field=models.CharField(default='5:00 AM - 5:00 AM', max_length=100, verbose_name='scheduledate'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='scheduleddate',
            field=models.CharField(default='5:00 AM - 5:00 AM', max_length=100, verbose_name='scheduledate'),
        ),
    ]
