# Generated by Django 4.0.2 on 2022-05-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0006_alter_repre_scheduleddate_alter_voter_scheduleddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='repre',
            name='forscheduling',
            field=models.BooleanField(default=False, verbose_name='forscheduling'),
        ),
        migrations.AddField(
            model_name='voter',
            name='forscheduling',
            field=models.BooleanField(default=False, verbose_name='forscheduling'),
        ),
    ]
