# Generated by Django 4.0.2 on 2022-05-12 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0007_repre_forscheduling_voter_forscheduling'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Faci',
            new_name='Facis',
        ),
    ]
